### ISSUE TITLE
when trying to launch main throws error

### ISSUE THREAD

**Issue by orkfpot** [finneyj/SaadBall#5]
returns the output
```
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at GameArena.init(GameArena.java:79)
	at GameArena.<init>(GameArena.java:57)
	at Main.main(Main.java:5)
```

**Comment by ezzini** [comment]
Can you check if your environment is headless:[GraphicsEnvironment.isHeadless()](http://download.oracle.com/javase/6/docs/api/java/awt/GraphicsEnvironment.html#isHeadless%28%29) (support display).

You might need to install full JRE/JDK if this is the case:
```bash
sudo apt-get install openjdk-17-jdk
```
Or
```bash
sudo apt-get install openjdk-17-jre
```
you can install a different version if you want (replace 17 with 21 for example).

**Comment by ezzini** [comment]
Closing for now
